### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by DaruBrub** [Clan-Labs/RoGo#13]
When I tried `go get github.com/Clan-Labs/RoGo`, it errors, so how do I download it? What do i need to install in order for this work? Yes, i have git.

**Comment by echnobas** [comment]
works fine for me, please show the error so I can try and assist you further. please note that this repository is not currently actively being maintained.

**Comment by DaruBrub** [comment]
package github.com/Clan-Labs/RoGo: no Go files in C:\Users\CrashBandicoot\go\src\github.com\Clan-Labs\RoGo

**Comment by DaruBrub** [comment]
package github.com/Clan-Labs/RoGo: no Go files in $(some info i wont tell)go\src\github.com\Clan-Labs\RoGo

**Comment by echnobas** [comment]
are you using go modules?

**Comment by DaruBrub** [comment]
What do you mean?

**Comment by echnobas** [comment]
https://blog.golang.org/using-go-modules

**Comment by DaruBrub** [comment]
No, I don't think I am using go modules

**Comment by echnobas** [comment]
try using go modules, start your project by going into the directory of choice and doing `go mod init main`  and then try using go get
